/**
 * Shared Blueprint Rendering Utilities
 *
 * Extracts duplicated rendering logic from main-panel.js and blueprint-tabs.js
 * into reusable functions. Both the sidebar preview and settings-dialog overview
 * tab call these helpers so card markup stays consistent.
 */

import { isStyleMissing } from '../../blueprint/missing-style-handler.js';
import * as BlueprintModule from '../../blueprint/module.js';
import { escapeHtml } from '../component-system.js';

/**
 * Resolve the human-readable author style name for a blueprint.
 *
 * Resolution order:
 *  1. `blueprint.author_style_name` (embedded in the blueprint itself)
 *  2. Library lookup by `blueprint.author_style` ID
 *  3. `chatState.selectedAuthorStyle` (current chat fallback)
 *  4. `'None'`
 *
 * @param {Object} blueprint
 * @param {Array} authorStyles - Full author-styles array from state manager
 * @param {Object} [chatState] - Optional chat state for fallback lookup
 * @returns {string} Display name
 */
export function resolveAuthorStyleDisplayName(blueprint, authorStyles, chatState) {
    if (blueprint.author_style_name) {
        return blueprint.author_style_name;
    }
    if (blueprint.author_style) {
        const style = authorStyles.find(s => s.id === blueprint.author_style);
        return style?.name || blueprint.author_style;
    }
    if (chatState?.selectedAuthorStyle) {
        const style = authorStyles.find(s => s.id === chatState.selectedAuthorStyle);
        return style?.name || chatState.selectedAuthorStyle;
    }
    return 'None';
}

/**
 * Analyse which styles a blueprint references that are missing from the
 * user's local library.
 *
 * Detects two flavours of "missing author style":
 *  - ID-based: blueprint has `author_style` but that ID isn't in the library
 *  - Inline-only: blueprint has `author_style_name` + `author_style_prompt`
 *    but **no** `author_style` ID (the style was never saved to the library)
 *
 * @param {Object} blueprint
 * @returns {{
 *   storyTypeId: string|undefined,
 *   authorStyleId: string|undefined,
 *   storyTypeMissing: boolean,
 *   authorStyleMissing: boolean,
 *   hasEmbeddedStoryType: boolean,
 *   hasEmbeddedAuthorStyle: boolean,
 *   hasInlineAuthorStyle: boolean,
 * }}
 */
export function analyzeMissingStyles(blueprint) {
    const storyTypeId = blueprint.story_type_id;
    const authorStyleId = blueprint.author_style;

    const storyTypeMissing = !!storyTypeId && isStyleMissing('storyType', storyTypeId);

    // Inline-only author style: name + prompt present but no saved ID
    const hasInlineAuthorStyle = !authorStyleId
        && !!blueprint.author_style_name
        && !!blueprint.author_style_prompt;

    const authorStyleMissing =
        (!!authorStyleId && isStyleMissing('authorStyle', authorStyleId))
        || hasInlineAuthorStyle;

    const hasEmbeddedStoryType = storyTypeMissing && !!blueprint.embeddedResources?.storyType;
    const hasEmbeddedAuthorStyle = authorStyleMissing
        && !!(blueprint.embeddedResources?.authorStyle || hasInlineAuthorStyle);

    return {
        storyTypeId,
        authorStyleId,
        storyTypeMissing,
        authorStyleMissing,
        hasEmbeddedStoryType,
        hasEmbeddedAuthorStyle,
        hasInlineAuthorStyle,
    };
}

/**
 * Render the standard 4-column info-card row (Story Type, Author Style,
 * Total Scenes, Story Length). Returns raw `<div>` cards **without** a
 * wrapper — callers supply their own container class and may append extra
 * cards (e.g. "Generated By").
 *
 * @param {Object} blueprint
 * @param {Object} styleAnalysis - Output of {@link analyzeMissingStyles}
 * @param {string} authorStyleName - Resolved display name
 * @param {Object} [options]
 * @param {boolean} [options.includeInlineAttr=false] - Add `data-has-inline`
 *   on the author-style "Add" button (blueprint-tabs handler needs it).
 * @returns {string} HTML string of four `storymode-info-card` divs
 */
export function renderInfoCards(blueprint, styleAnalysis, authorStyleName, options = {}) {
    const {
        storyTypeId,
        authorStyleId,
        storyTypeMissing,
        authorStyleMissing,
        hasEmbeddedStoryType,
        hasEmbeddedAuthorStyle,
        hasInlineAuthorStyle,
    } = styleAnalysis;

    const includeInline = options.includeInlineAttr ?? false;

    const storyTypeCard = `
        <div class="storymode-info-card${storyTypeMissing ? ' storymode-missing-style' : ''}">
            <label>Story Type</label>
            <span>${escapeHtml(blueprint.story_type_name || blueprint.story_type_id || 'Unknown')}</span>
            ${storyTypeMissing ? `
            <button class="menu_button storymode-add-style-btn"
                data-style-type="storyType"
                data-style-id="${escapeHtml(storyTypeId)}"
                data-style-name="${escapeHtml(blueprint.story_type_name || '')}"
                data-has-embedded="${hasEmbeddedStoryType ? 'true' : 'false'}"
                title="${hasEmbeddedStoryType ? 'Import this story type' : 'Create this story type manually'}">
                <i class="fa-solid fa-plus"></i> Add
            </button>` : ''}
        </div>`;

    const inlineAttr = includeInline && hasInlineAuthorStyle
        ? ' data-has-inline="true"'
        : '';

    const authorStyleCard = `
        <div class="storymode-info-card${authorStyleMissing ? ' storymode-missing-style' : ''}">
            <label>Author Style</label>
            <span>${escapeHtml(authorStyleName)}</span>
            ${authorStyleMissing ? `
            <button class="menu_button storymode-add-style-btn"
                data-style-type="authorStyle"
                data-style-id="${escapeHtml(authorStyleId || '')}"
                data-style-name="${escapeHtml(blueprint.author_style_name || '')}"
                data-has-embedded="${hasEmbeddedAuthorStyle ? 'true' : 'false'}"${inlineAttr}
                title="${hasEmbeddedAuthorStyle ? 'Import this author style to your library' : 'Create this author style manually'}">
                <i class="fa-solid fa-plus"></i> Add
            </button>` : ''}
        </div>`;

    const scenesCard = `
        <div class="storymode-info-card">
            <label>Total Scenes</label>
            <span>${blueprint.scene_plan?.length || 0}</span>
        </div>`;

    const lengthCard = `
        <div class="storymode-info-card">
            <label>Story Length</label>
            <span>${BlueprintModule.calculateTotalRounds(blueprint)} rounds</span>
        </div>`;

    return storyTypeCard + authorStyleCard + scenesCard + lengthCard;
}

/**
 * Render the "current scene" card showing title, meta line, and purpose.
 *
 * Returns the inner `.storymode-scene-card.current` div. Callers can wrap
 * it in their own container (blueprint-tabs wraps in a `.storymode-card`
 * with a header; main-panel uses it directly).
 *
 * @param {Object} currentScene - Scene object (must have .index at minimum)
 * @param {Object} blueprint - Full blueprint (for scene_plan.length)
 * @param {Object} [options]
 * @param {string} [options.extraContent=''] - HTML appended inside the card
 *   (main-panel uses this for beat progress).
 * @returns {string} HTML string
 */
export function renderCurrentSceneCard(currentScene, blueprint, options = {}) {
    const extra = options.extraContent || '';
    return `
        <div class="storymode-scene-card current">
            <div class="storymode-scene-title">${escapeHtml(currentScene.title || 'Untitled')}</div>
            <div class="storymode-scene-meta">
                Scene ${currentScene.index + 1}/${blueprint.scene_plan?.length || 0} • ${escapeHtml(currentScene.phase || 'Unknown')}
            </div>
            ${currentScene.purpose ? `<p style="margin-top: 8px; font-size: 0.9em; color: var(--SmartThemeBodyColor);">${escapeHtml(currentScene.purpose)}</p>` : ''}
            ${extra}
        </div>`;
}
