/**
 * Panel Renderers Module
 * Renders left panel (blueprint info) and right panel (tabbed editor)
 */

import { escapeHtml } from '../../blueprint/utils.js';
import { getCurrentBlueprint, getActiveTab, getHasUnsavedChanges } from './state.js';

// Tab renderer imports
import { renderDetailsTab } from './details-tab.js';
import { renderScenesTab } from './scenes-tab.js';
import { renderCoverTab } from './cover-tab.js';
import { renderCharactersTab } from './characters-tab.js';

// ============================================================================
// LEFT PANEL
// ============================================================================

/**
 * Render Left Panel content
 * Shows blueprint metadata
 * @returns {string} HTML content
 */
export function renderLeftPanel() {
    const bp = getCurrentBlueprint();
    const id = bp.blueprint_id || 'N/A';
    const shortId = id.length > 12 ? `${id.substring(0, 8)}...` : id;
    const title = bp.blueprint_title || 'Untitled Blueprint';
    const createdDate = bp.created_at ? new Date(bp.created_at).toLocaleDateString() : new Date().toLocaleDateString();
    const modifiedDate = bp.modified_at ? new Date(bp.modified_at).toLocaleDateString() : 'Just now';

    return `
        <div class="storymode-editor-left-panel">
            <div class="storymode-blueprint-info">
                <h3 class="storymode-blueprint-title">${escapeHtml(title)}</h3>
                <p style="margin: 0 0 12px 0; font-size: 0.85em; opacity: 0.7;">Blueprint Info</p>
                <div class="storymode-info-field">
                    <label>ID:</label>
                    <span class="monospace">${escapeHtml(shortId)}</span>
                </div>
                <div class="storymode-info-field">
                    <label>Story Type:</label>
                    <span>${escapeHtml(bp.story_type_name || 'Unknown')}</span>
                </div>
                <div class="storymode-info-field">
                    <label>Author Style:</label>
                    <span>${escapeHtml(bp.author_style_name || 'None')}</span>
                </div>
                <div class="storymode-info-field">
                    <label>Story Length:</label>
                    <span>${bp.arc_structure?.total_messages_target || 30} rounds</span>
                </div>
                <div class="storymode-info-field">
                    <label>Scenes:</label>
                    <span>${bp.scene_plan?.length || 0} scenes</span>
                </div>
                <div class="storymode-info-field">
                    <label>Generated By:</label>
                    <span>${escapeHtml(bp.llmDescriptor || 'Unknown')}</span>
                </div>
                <hr>
                <div class="storymode-info-field">
                    <label>Created:</label>
                    <span>${escapeHtml(createdDate)}</span>
                </div>
                <div class="storymode-info-field">
                    <label>Last Modified:</label>
                    <span>${escapeHtml(modifiedDate)}</span>
                </div>
            </div>
            <div class="storymode-editor-play-btn-container">
                <button id="blueprint_editor_play_btn" class="storymode-btn-start storymode-editor-play-btn" title="Start story from this blueprint">
                    <i class="fa-solid fa-play"></i>
                </button>
            </div>
        </div>
    `;
}

// ============================================================================
// RIGHT PANEL
// ============================================================================

/**
 * Render Right Panel content (tabbed editor)
 * @returns {string} HTML content
 */
export function renderRightPanel() {
    return `
        <div class="storymode-editor-right-panel">
            <div class="storymode-editor-header">
                <div class="storymode-editor-tabs">
                    <button class="storymode-tab ${getActiveTab() === 'details' ? 'active' : ''}" data-tab="details">
                        <i class="fa-solid fa-file-lines"></i> Details
                    </button>
                    <button class="storymode-tab ${getActiveTab() === 'characters' ? 'active' : ''}" data-tab="characters" title="View and manage character arcs">
                        <i class="fa-solid fa-users"></i> Characters
                    </button>
                    <button class="storymode-tab ${getActiveTab() === 'scenes' ? 'active' : ''}" data-tab="scenes">
                        <i class="fa-solid fa-film"></i> Scenes
                    </button>
                    <button class="storymode-tab ${getActiveTab() === 'cover' ? 'active' : ''}" data-tab="cover">
                        <i class="fa-solid fa-image"></i> Cover
                    </button>
                </div>
            </div>
            <div class="storymode-editor-content">
                ${renderTabContent()}
            </div>
        </div>
    `;
}

/**
 * Render the active tab content
 * @returns {string} HTML content
 */
export function renderTabContent() {
    switch (getActiveTab()) {
        case 'details':
            return renderDetailsTab();
        case 'scenes':
            return renderScenesTab();
        case 'cover':
            return renderCoverTab();
        case 'characters':
            return renderCharactersTab();
        default:
            return renderDetailsTab();
    }
}
